#!/bin/bash
# mkdosswapfile - create sidux swapfile on a existing DOS partition
# (C) Klaus Knopper Mar 2001
# (C) 2005-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de>

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

XDIALOG_HIGH_DIALOG_COMPAT=1
export XDIALOG_HIGH_DIALOG_COMPAT

TMP="$(mktemp -p /tmp/ mkdosswapfile-XXXXXXXXXX)"

# override tool behaviour through distro-defaults
FLL_DISTRO_NAME="sidux"
FLL_LIVE_USER="sidux"
[ -r /etc/default/distro ] && . /etc/default/distro


bailout() {
	rm -f "$TMP"
	exit 0
}

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"

trap bailout 1 2 3 15

DOSPARTITIONS=""

# Find all DOS partitions
if [ -f /proc/partitions ]; then
	partitions=""
		for p in $(awk 'BEGIN{old="__start"}{if($0==old){exit}else{old=$0;if($4&&$4!="name"){print $4}}}' /proc/partitions); do
			
			case $p in
				hd?|sd?|ub?)
					partitions="$partitions /dev/$p"
					;;
				*)
					;;
			esac
		done

		if [ -n "$partitions" ]; then
			foundp="$(LANG=C LC_ALL=C fdisk -l $partitions 2>/dev/null)"
			for p in `echo "$foundp" | awk '/^\/dev\//{if(/FAT/){print $1}}'`; do
				d="/media/${p##*/}"
					if mount -o ro -t vfat "$p" "$"d 2>/dev/null; then
						[ ! -f $d/$FLL_LIVE_USER.swp ] && DOSPARTITIONS="$DOSPARTITIONS $p"
						umount "$d"
					fi
			done
		fi
fi

if [ -n "$DOSPARTITIONS" ]; then
	echo -n "c"
	
	for p in $DOSPARTITIONS; do
		# Language-dependent Messages
		case "$LANG" in
			de*|at*|ch*)
				MESSAGE1="Möchten Sie eine SWAP-Datei '$FLL_LIVE_USER.swp' für $FLL_DISTRO_NAME auf Ihrer bestehenden DOS-Partition $p anlegen? Eine solche SWAP-Datei ermöglicht es Ihnen, trotz geringem Hauptspeicher Programmpakete wie KDE zu benutzen. Sie können diese Datei nach Beendigung Ihrer $FLL_DISTRO_NAME-Session gefahrlos wieder löschen."
				MESSAGE2="Bitte geben Sie an, wieviel MB Sie als SWAP verwenden wollen. Empfohlen: 60 - 128. Frei: "
				MESSAGE3="Erzeuge swapfile '$FLL_LIVE_USER.swp' auf $p..."
				ERROR1="Leider ist nicht genug Platz auf dieser Partition ($p), es sollten mindestens 60 MB frei sein."
				SUCCESS="Das Einrichten des Swapfiles '$FLL_LIVE_USER.swp' auf $p war erfolgreich."
				;;
			es*)
				MESSAGE1="¿Quiere crear un fichero de memoria virtual (swap) '$FLL_LIVE_USER.swp' en su partición DOS existente $p? Un fichero swap le permite utilizar grandes aplicaciones como KDE incluso si su ordenador tiene poca memoria. Puede borrar tranquilamente el fichero swap una vez haya finalizado su sesión con $FLL_DISTRO_NAME."
				MESSAGE2="Por favor, especifique la cantidad de espacio en disco que quiere utilizar como SWAP. Recomendado: 60 - 128. Libre: "
				MESSAGE3="Creando archivo de memoria virtual '$FLL_LIVE_USER.swp' en $p..."
				ERROR1="Lo siento, no hay suficiente espacio libre en $p. Son necesarios al menos 60 MB."
				SUCCESS="Archivo swap '$FLL_LIVE_USER.swp' en $p creado satisfactoriamente."
				;;
			*)
				MESSAGE1="Do you want to create a swapfile '$FLL_LIVE_USER.swp' on your existing DOS partition $p? A swapfile allows you to use huge application packages like KDE even if your computer is low on memory. You can safely delete the swapfile after finishing your $FLL_DISTRO_NAME session."
				MESSAGE2="Please specify the amount of diskspace that you want to use as SWAP. Recommended: 60 - 128. Free: "
				MESSAGE3="Creating swapfile '$FLL_LIVE_USER.swp' on $p..."
				ERROR1="Sorry, not enough free space on $p. At least 60 MB required."
				SUCCESS="Swapfile '$FLL_LIVE_USER.swp' on $p successfully created."
				;;
		esac

		d="/media/${p##*/}"
		f="$d/$FLL_LIVE_USER.swp"
		if mount -o umask=000,rw -t vfat $p $d; then
			if $DIALOG --yesno "$MESSAGE1" 11 62; then
				AVAIL="$(df -m $DIRECTORY | tail -1 | awk '{print $4}')"
				if [ "$AVAIL" -lt 60 ]; then
					$DIALOG --msgbox "$ERROR1" 10 45
					umount "$d"
				else
					rm -f "$TMP"
					$DIALOG --inputbox "$MESSAGE2 $AVAIL" 8 62 "60" 2>"$TMP" || { umount "$d" ; bailout; }
					IN="`cat $TMP`" 
					[ "$IN" -ge 60 -a "$IN" -le "$AVAIL" ] 2>/dev/null || IN="60"
					echo "$MESSAGE3"
					
					dd if=/dev/zero of="$f" bs=1000k count="$IN" && \
						mkswap -v1 "$f" && swapon -v "$f" 2>/dev/null && \
						echo "$f swap swap defaults 0 0" >>/etc/fstab
					[ "$?" = "0" ] && { sleep 2 ; $DIALOG --msgbox "$SUCCESS" 10 45; } || umount "$d" 2>/dev/null
					
					mount -o remount,ro $d
				fi
			else
				umount "$d"
			fi
		fi
	done
else
	case "$LANG" in
		de*|at*|ch*)
			ERROR2="Leider sind auf Ihrem System keine geeigneten DOS-Partitionen zum Einrichten eines Swapfile vorhanden."
			;;
		es*)
			ERROR2="Lo siento, no se han encontrado particiones disponibles de tipo DOS para el fichero swap de memoria virtual."
			;;
		*)
			ERROR2="Sorry, no DOS partitions available for swapfile."
			;;
	esac

	$DIALOG --msgbox "$ERROR2" 10 45
fi

bailout

